# Generated by Django 4.1.3 on 2022-11-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='servers',
            new_name='serves',
        ),
    ]
